export const breedsData = [
    {name:'Affenpinscher'},
    {name:'Affrican'},
    {name:'Airedale'},
    {name:'Akita'},
    {name:'Appenzeller'},
    {name:'Shepherd Australian'},
    {name:'Basenji'},
    {name:'Beagle'},
    {name:'Bluetick'},
    {name:'Borzoi'},
    {name:'Bouvier'},
    {name:'Boxer'},
    {name:'Brabacon'},
    {name:'Briard'},
    {name:'Norwegian Buhund'},
    {name:'Boston Bulldog'},
    {name:'English Bulldog'},
    {name:'French Bulldog'},
    {name:'Staffordshire Bullterrier'},
    {name:'Cairn'},
    {name:'Australian Cattledog'},
    {name:'Chihuahua'},
    {name:'Chow'},
    {name:'Clumber'},
    {name:'Cockapoo'},
    {name:'Border Collie'},
    {name:'Coonhound'},
    {name:'Cardigan Corgi'},
    {name:'Cotondetulear'},
    {name:'Dachshund'},
    {name:'Dalmatian'},
    {name:'Great Dane'},
    {name:'Scottish Deerhound'},
    {name:'Dhole'},
    {name:'Dingo'},
    {name:'Doberman'},
    {name:'Norwegian Elkhound'},
    {name:'Entlebucher'},
    {name:'Eskimo'},
    {name:'Lapphund Finnish'},
    {name:'Bichon Frise'},
    {name:'Germanshepherd'},
    {name:'Italian Greyhound'},
    {name:'Groenendael'},
    {name:'Havanese'},
    {name:'Afghan Hound'},
    {name:'Basset Hound'},
    {name:'Blood Hound'},
    {name:'English Hound'},
    {name:'Ibizan Hound'},
    {name:'Plott Hound'},
    {name:'Walker Hound'},
    {name:'Husky'},
    {name:'Keeshond'},
    {name:'Kelpie'},
    {name:'Komondor'},
    {name:'Kuvasz'},
    {name:'Labrador'},
    {name:'Leonberg'},
    {name:'Lhasa'},
    {name:'Malamute'},
    {name:'Malinois'},
    {name:'Maltese'},
    {name:'Bull Mastiff'},
    {name:'English Mastiff'},
    {name:'Tibetan Mastiff'},
    {name:'Mexicanhairless'},
    {name:'Mix'},
    {name:'Bernese Mountain'},
    {name:'Swiss Mountain'},
    {name:'Newfoundland'},
    {name:'Otterhound'},
    {name:'Caucasian Ovcharka'},
    {name:'Papillon'},
    {name:'Pekinese'},
    {name:'Pembroke'},
    {name:'Miniature Pinscher'},
    {name:'Pitbull'},
    {name:'German Pointer'},
    {name:'Germanlonghair Pointer'},
    {name:'Pomeranian'},
    {name:'Miniature Poodle'},
    {name:'Standard Poodle'},
    {name:'Toy Poodle'},
    {name:'Pug'},
    {name:'Puggle'},
    {name:'Pyreness'},
    {name:'Redbone'},
    {name:'Chesapeake Retriever'},
    {name:'Curly Retriever'},
    {name:'Flatcoated Retriever'},
    {name:'Golden Retriever'},
    {name:'Rhodesian Ridgeback'},
    {name:'Rottweiler'},
    {name:'Saluki'},
    {name:'Samoyed'},
    {name:'Schipperke'},
    {name:'Giant Schnauzer'},
    {name:'Miniature Schnauzer'},
    {name:'English Setter'},
    {name:'Gordon Setter'},
    {name:'Irish Setter'},
    {name:'English Sheepdog'},
    {name:'Shetland Sheepdog'},
    {name:'Shiba'},
    {name:'Shihtzu'},
    {name:'Blenheim Spaniel'},
    {name:'Brittany Spaniel'},
    {name:'Cocker Spaniel'},
    {name:'Irish Spaniel'},
    {name:'Japanese Spaniel'},
    {name:'Sussex Spaniel'},
    {name:'Welsh Spaniel'},
    {name:'English Springer'},
    {name:'Stbernard'},
    {name:'American Terrier'},
    {name:'Australian Terrier'},
    {name:'Bedlington Terrier'},
    {name:'Border Terrier'},
    {name:'Bandie Terrier'},
    {name:'Fox Terrier'},
    {name:'Irish Terrier'},
    {name:'Kerryblue Terrier'},
    {name:'Lakeland Terrier'},
    {name:'NorFolk Terrier'},
    {name:'Norwich Terrier'},
    {name:'Patterdale Terrier'},
    {name:'Russell Terrier'},
    {name:'Scottish Terrier'},
    {name:'Sealyham Terrier'},
    {name:'Silky Terrier'},
    {name:'Tibetan Terrier'},
    {name:'Toy Terrier'},
    {name:'Westhighland Terrier'},
    {name:'Wheaten Terrier'},
    {name:'Yorkshire Terrier'},
    {name:'Vizsla'},
    {name:'Spanish Waterdog'},
    {name:'Weimaraner'},
    {name:'Irish Wolfhound'},
]